services:
  dragonfly:
    image: "docker.dragonflydb.io/dragonflydb/dragonfly"
    networks:
      - chat 
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    command: ["--maxmemory", "256mb", "--proactor_threads", "1"]

  traefik:
    image: "traefik:v3.6"
    security_opt:
      - no-new-privileges:true
    networks:
      - chat 
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      - TRAEFIK_DASHBOARD_PASS:${TRAEFIK_DASHBOARD_PASS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker_volumes/certs:/certs:ro
      - ./docker_volumes/dynamic:/etc/traefik/dynamic:ro
    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"

      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=chat"
      - "--providers.file.directory=/etc/traefik/dynamic"

      - "--api.dashboard=true"
      - "--api.insecure=true"

      - "--log.level=INFO"
      - "--accesslog=true"
      - "--metrics.prometheus=true"
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.dashboard.rule=Host(`dashboard.docker.localhost`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"

      - "traefik.http.middlewares.dashboard-auth.basicauth.users=${TRAEFIK_DASHBOARD_PASS}"
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth@docker"
  chat:
    build: .
    environment:
      ENVIRONMENT: "PRODUCTION"
      REDIS_URL: "redis://dragonfly:6379"
      OTLP_HTTP_URL: "http://otlp_collector:4318" 
    networks:
      - chat 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chat.rule=Host(`chat.docker.localhost`)"
      - "traefik.http.routers.chat.entrypoints=websecure"
      - "traefik.http.routers.chat.tls=true"
      - "traefik.http.routers.chat.service=chat_service"
      - "traefik.http.services.chat_service.loadbalancer.sticky.cookie=true"
      - "traefik.http.services.chat_service.loadbalancer.sticky.cookie.name=chat_sticky_cookie"
      - "traefik.http.services.chat_service.loadbalancer.sticky.cookie.secure=true"
    deploy:
      mode: replicated
      replicas: 1

  otlp_collector:
    image: "otel/opentelemetry-collector-contrib:0.141.0"
    volumes:
      - ./otel_config.yaml:/etc/otelcol/config.yaml
    command: ["--config=/etc/otelcol/config.yaml"]
    networks:
      - chat 

  victoria_metrics:
    image: "victoriametrics/victoria-metrics:v1.131.0"
    volumes:
      - ./docker_volumes/metrics:/victoria-metrics-data
    environment:
      storageDataPath: "victoria-metrics-data"
      retentionPeriod: "1d"
    networks:
      - chat 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.victoria_metrics.rule=Host(`victoria_metrics.docker.localhost`)"
      - "traefik.http.routers.victoria_metrics.entrypoints=websecure"
      - "traefik.http.routers.victoria_metrics.tls=true"
      - "traefik.http.routers.victoria_metrics.service=victoria_metrics_service"
      - "traefik.http.services.victoria_metrics_service.loadbalancer.server.port=8428"

  victoria_logs:
    image: "victoriametrics/victoria-logs:v1.40.0"
    volumes:
      - ./docker_volumes/logs:/victoria-metrics-data
    environment:
      storageDataPath: "victoria-metrics-data"
      retentionPeriod: "1d"
    networks:
      - chat 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.victoria_logs.rule=Host(`victoria_logs.docker.localhost`)"
      - "traefik.http.routers.victoria_logs.entrypoints=websecure"
      - "traefik.http.routers.victoria_logs.tls=true"
      - "traefik.http.routers.victoria_logs.service=victoria_logs_service"
      - "traefik.http.services.victoria_logs_service.loadbalancer.server.port=9428"

  jaeger:
    image: "cr.jaegertracing.io/jaegertracing/jaeger:2.13.0" 
    networks:
    - chat 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jaeger.rule=Host(`jaeger.docker.localhost`)"
      - "traefik.http.routers.jaeger.entrypoints=websecure"
      - "traefik.http.routers.jaeger.tls=true"
      - "traefik.http.routers.jaeger.service=jaeger_service"
      - "traefik.http.services.jaeger_service.loadbalancer.server.port=16686"

  stats:
    image: "drakonis96/dockerstats:latest"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stats.rule=Host(`stats.docker.localhost`)"
      - "traefik.http.routers.stats.entrypoints=websecure"
      - "traefik.http.routers.stats.tls=true"
      - "traefik.http.routers.stats.service=stats_service"
      - "traefik.http.services.stats_service.loadbalancer.server.port=5001"


networks:
  chat:
    name: chat
