FROM oven/bun:1.3.6-alpine AS compiler 
WORKDIR /usr/src/app
COPY package.json bun.lock .
COPY ./app ./app
RUN bun install --frozen-lockfile --production
RUN bun build --production --compile --minify --sourcemap=inline --outfile=bun_websocket --target=bun-linux-x64-musl ./app/index.ts 
RUN apk --no-cache add upx
RUN upx bun_websocket 

FROM alpine:3.23.2 AS runner
RUN apk add --no-cache libstdc++
WORKDIR /usr/src/app
COPY --from=compiler /usr/src/app/bun_websocket .
EXPOSE 3000/tcp
ENTRYPOINT [ "./bun_websocket" ]
