services:
  dragonfly:
    image: "docker.dragonflydb.io/dragonflydb/dragonfly"
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    command: ["--maxmemory", "256mb", "--proactor_threads", "1"]

  otlp_collector:
    image: "otel/opentelemetry-collector-contrib:0.141.0"
    volumes:
      - ./otel_config.yaml:/etc/otelcol/config.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    group_add:
      - 987 # Docker group
    command: ["--config=/etc/otelcol/config.yaml"]
    ports:
      - "4317:4317"
    networks:
      - chat

  grafana:
    image: "grafana/grafana:12.4.0-19350470871"
    volumes:
      - ./docker_volumes/grafana:/var/lib/grafana
      - ./datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    ports:
      - "3001:3000"
    networks:
      - chat
    environment:
      GF_PLUGINS_PREINSTALL: victoriametrics-metrics-datasource,victoriametrics-logs-datasource
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.docker.localhost`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.service=grafana_service"
      -   

  victoria_metrics:
    image: "victoriametrics/victoria-metrics:v1.131.0"
    volumes:
      - ./docker_volumes/metrics:/victoria-metrics-data
    environment:
      storageDataPath: "victoria-metrics-data"
      retentionPeriod: "1d"
    networks:
      - chat

  victoria_logs:
    image: "victoriametrics/victoria-logs:v1.40.0"
    volumes:
      - ./docker_volumes/logs:/victoria-metrics-data
    environment:
      storageDataPath: "victoria-metrics-data"
      retentionPeriod: "1d"
    networks:
      - chat

  jaeger:
    image: "cr.jaegertracing.io/jaegertracing/jaeger:2.13.0" 
    networks:
      - chat 
    ports:
      - "16686:16686"

  zipkin:
    image: "openzipkin/zipkin:3.6"
    networks:
      - chat
    ports:
      - "9411:9411"

networks:
  chat:
    name: chat
