receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ":4317"

  docker_stats:
    endpoint: unix:///var/run/docker.sock
    collection_interval: 5s

exporters:

  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

  zipkin/nontls:
    endpoint: http:/zipkin:9411/api/v2/spans
    format: proto
    default_service_name: unknown-service
    tls:
      insecure: true

  otlphttp:
    logs_endpoint: http://victoria_logs:9428/insert/opentelemetry/v1/logs
    metrics_endpoint: http://victoria_metrics:8428/opentelemetry/v1/metrics
    tls:
      insecure: true
    encoding: proto
    compression: gzip

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [otlphttp]

    metrics:
      receivers: [otlp]
      exporters: [otlphttp]

    traces:
      receivers: [otlp]
      exporters: [otlp/jaeger, zipkin/nontls]

