run_01:
	npx ts-node 01_tipos_implicitos_explicitos.ts
run_02:
	npx ts-node 02_tuplas.ts
run_04:
	npx ts-node 04_generics.ts
run_05:
	npx ts-node 05_typing_legacy_functions.ts
run_06:
	npx ts-node 06_last_tips.ts