run_01:
	npx ts-node 01_types_implicits_explicits.ts
run_02:
	npx ts-node 02_tuplas.ts
run_04:
	npx ts-node 04_generics.ts
run_05:
	npx ts-node 05_typing_legacy_functions.ts
run_06:
	npx ts-node 06_typing_with_generics.ts
run_07:
	npx ts-node 07_last_tips.ts